
CREATE TABLE IF NOT EXISTS Client (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      cnp VARCHAR(13) NOT NULL,
    nume VARCHAR(255),
    prenume VARCHAR(255),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_utilizator PRIMARY KEY (id),
    CONSTRAINT chk_cnp_length CHECK (LENGTH(cnp) = 13 AND cnp REGEXP '^[0-9]{13}$'),
    CONSTRAINT uk_cnp UNIQUE (cnp)
    );

CREATE TABLE IF NOT EXISTS Account (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       client_id BIGINT NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES Client(id)
    );


CREATE TABLE IF NOT EXISTS ActiuniBancare (
                                              id_action BIGINT AUTO_INCREMENT PRIMARY KEY,
                                              ID BIGINT NOT NULL,
    depunere DECIMAL(10, 2),
    retragere DECIMAL(10, 2),
    tranzactie DECIMAL(10, 2),
    data_ora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilizator FOREIGN KEY (ID) REFERENCES Client(id)
    );

